import streamlit as st
import joblib
from pathlib import Path
from preprocess import clean_text  # Imports your team's custom text cleaner
def validate_ticket_input(text):
    """Validates ticket length and checks for dictionary gibberish."""
    # Length Thresholding
    raw_words = text.split()
    if len(raw_words) < 5:
        return False, "Ticket is too short. Please provide at least 3 words."
    if len(raw_words) >= 500:
        return False, "Ticket is too long. Please summarize the issue."

    return True, "Valid"

# 1. Set up the page design
st.set_page_config(page_title="IT Ticket Triage AI", page_icon="🎫", layout="centered")

BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_DIR = BASE_DIR / 'prototype' /'model'
VEC_DIR = BASE_DIR / 'prototype' /'vectorizer'
# --- MODEL DICTIONARIES ---
# Here we map the dropdown names to their exact saved file names. 
# When your team finishes the Transformer model, you can just add it to these lists!
DEPT_MODELS = {
    "Naive Bayes": (MODEL_DIR / "nb_department_model.pkl", VEC_DIR / "tfidf_nb_department_vectorizer.pkl"),
    "SVM": (MODEL_DIR / "svm_department_model.pkl", VEC_DIR / "tfidf_svm_department_vectorizer.pkl"),
    "Logistic Regression": (MODEL_DIR / "logreg_department_model.pkl",
                            VEC_DIR / "tfidf_logreg_department_vectorizer.pkl")
}

PRIORITY_MODELS = {
    "Naive Bayes": (MODEL_DIR / "nb_priority_model.pkl", VEC_DIR / "tfidf_nb_priority_vectorizer.pkl"),
    "SVM": (MODEL_DIR / "svm_priority_model.pkl", VEC_DIR / "tfidf_svm_priority_vectorizer.pkl"),
    "Logistic Regression": (MODEL_DIR / "logreg_priority_model.pkl", VEC_DIR / "tfidf_logreg_priority_vectorizer.pkl")
}

# 2. Dynamic Model Loader
# Passing the filenames as arguments allows Streamlit to cache each model efficiently
@st.cache_resource
def load_selected_model(model_path, vec_path):
    model = joblib.load(model_path)
    vectorizer = joblib.load(vec_path)
    return model, vectorizer

# --- UI LAYOUT ---
st.title("🎫 Automated IT Ticket Triage")
st.write("Enter a customer support ticket below, and our AI will automatically route it to the correct department and assign a priority level.")

# 3. Sidebar for Model Selection
st.sidebar.header("⚙️ Settings")
st.sidebar.write("Select the underlying AI models for the triage system:")

selected_dept_model = st.sidebar.selectbox("Department Routing Model", list(DEPT_MODELS.keys()))
selected_pri_model = st.sidebar.selectbox("Priority Prediction Model", list(PRIORITY_MODELS.keys()))

# Retrieve the correct filenames based on what the user clicked in the sidebar
dept_model_file, dept_vec_file = DEPT_MODELS[selected_dept_model]
pri_model_file, pri_vec_file = PRIORITY_MODELS[selected_pri_model]

# Load the models with a try-except block in case a teammate hasn't provided their .pkl file yet
try:
    dept_model, dept_vec = load_selected_model(dept_model_file, dept_vec_file)
    pri_model, pri_vec = load_selected_model(pri_model_file, pri_vec_file)
except FileNotFoundError as e:
    st.error(f"⚠️ Missing file: {e}. Make sure you have trained and saved the {selected_dept_model} and {selected_pri_model} models to your folder.")
    st.stop()  # Stops the app from crashing further down

# 4. Create the user input area
st.subheader("Submit a New Ticket")
ticket_text = st.text_area("Ticket Body:", height=150, placeholder="e.g., URGENT: The main database server is down and no one can process payments! (5~500word)")

# 5. Process the text and make predictions
if st.button("Predict Triage Routing"):
    # Run our new validation function
    is_valid, validation_message = validate_ticket_input(ticket_text)

    if not is_valid:
        # Display the specific error message generated by the validation function
        st.warning(f"⚠️ {validation_message}")
    else:
        with st.spinner("Analyzing text..."):
            # Step A: Preprocess the raw text
            cleaned_text = clean_text(ticket_text, remove_custom_stopwords=True)
            
            # Step B: Vectorize and predict Department using the SELECTED model
            dept_vectorized = dept_vec.transform([cleaned_text])
            predicted_dept = dept_model.predict(dept_vectorized)[0]
            
            # Step C: Vectorize and predict Priority using the SELECTED model
            pri_vectorized = pri_vec.transform([cleaned_text])
            predicted_priority = pri_model.predict(pri_vectorized)[0]
            
            # Step D: Display the Results beautifully
            st.success("Analysis Complete!")
            
            col1, col2 = st.columns(2)
            
            with col1:
                # Adding the model name in brackets so the user knows which one made the decision
                st.metric(label=f"🏢 Routed Department ({selected_dept_model})", value=predicted_dept)
                
            with col2:
                if predicted_priority.lower() == "high":
                    st.metric(label=f"🚨 Urgency Priority ({selected_pri_model})", value=predicted_priority)
                else:
                    st.metric(label=f"📋 Urgency Priority ({selected_pri_model})", value=predicted_priority)